### ISSUE TITLE
Latitude E7270/E7470 version 1.22.8

### ISSUE THREAD

**Issue by stblr** [fwupd/missing-firmware-dell#11]
https://www.dell.com/support/home/us/en/04/drivers/driversdetails?driverid=wr9gj&oscode=biosa&productcode=latitude-e7470-ultrabook

https://fwupd.org/lvfs/device/com.dell.uefi212026ee.firmware

**Comment by superm1** [comment]
Thanks I've forwarded it to the right folks.

**Comment by superm1** [comment]
It's now in stable, thanks.
