### ISSUE TITLE
XPS 13 7390 2-in-1 support

### ISSUE THREAD

**Issue by guilhem** [fwupd/missing-firmware-dell#12]
XPS 13 7390 2-in-1 as no version right now.

Latest firmware:
- 1.0.13: https://www.dell.com/support/home/us/en/19/drivers/driversdetails?driverid=6xk8c&oscode=wt64a&productcode=xps-13-7390-2-in-1-laptop&lwp=rt

```
System Firmware
  DeviceId:             fb5523b663445df99fe178d162a221546e1974af
  Guid:                 20448dae-1dd2-5653-a2b3-c81b77007d2f
  Plugin:               uefi
  Flags:                internal|updatable|require-ac|registered|needs-reboot
  Checksum:             SHA1(76fe16309bcf04a887ae4f93e7ae27907c8bcaf6)
  Checksum:             SHA256(84af83c84a22dbff71f11ffb5b14e45d55ef6c08c45026a1e34ed0b5fd081222)
  Vendor:               Dell Inc.
  Version:              0.1.0.13
  VersionLowest:        0.1.0.13
  VersionFormat:        quad
  Icon:                 computer
  Created:              2019-11-06
```

**Comment by superm1** [comment]
Hi,

The XPS 13 7390 2-in-1 isn't available with Ubuntu, so the BIOS likely will not be posted to LVFS.
I would recommend for now you follow the instructions in https://github.com/fwupd/missing-firmware-dell to update the firmware on your system.
