### ISSUE TITLE
Missing update for Dell Optiplex 7060: 1.4.2

### ISSUE THREAD

**Issue by StricUmu** [fwupd/missing-firmware-dell#14]
For missing firmware please provide the following items:

* Link to firmware update at OEM website:
https://www.dell.com/support/home/se/sv/sebsdt1/drivers/driversdetails?driverid=td2nc&oscode=wt64a&productcode=optiplex-7060-desktop

* Firmware release date (if available on OEM website):
2019-07-05

* Link to the device page on LVFS.
https://fwupd.org/lvfs/devices/com.dell.uefidf35f706.firmware
https://fwupd.org/lvfs/search?value=optiplex+7060 (gives two hits..)

**Comment by superm1** [comment]
Thanks.
it's fixed now, all the various optiplexes from that family have the updates posted:

![image](https://user-images.githubusercontent.com/494526/72013257-26895500-3223-11ea-93e5-d8261723dba0.png)
