### ISSUE TITLE
Many Dell firmwares not updated to latest on LVFS

### ISSUE THREAD

**Issue by grigi** [fwupd/missing-firmware-dell#16]
Many Dell firmwares that used to get updated stopped getting updates in the last two months.
My system is a latitude 5490 so I list links here, but I noticed the same with 5x91.
The firmwares include security fixes, so I would prefer that they get updated.

Thanks in advance!

* Link to firmware update at OEM website: v1.12.1 (19 Dec 2019)
https://www.dell.com/support/home/za/en/zabsdt1/drivers/driversdetails?driverid=tpt7x&oscode=wt64a&productcode=latitude-14-5490-laptop

* Link to the device page on LVFS: v1.11.1 (4 Nov 2019)
https://fwupd.org/lvfs/devices/com.dell.ueficdcae5ae.firmware

**Comment by superm1** [comment]
@grigi I'll ping the right people to figure out why this didn't promote to stable yet.

@pshem please file a separate issue to track this for your system.

**Comment by grigi** [comment]
@superm1 Thank you, the firmwares have been updated! :+1:
