### ISSUE TITLE
Dell Inspiron Gaming missing latest BIOS updates

### ISSUE THREAD

**Issue by pshem** [fwupd/missing-firmware-dell#17]
| Source | Version | Updated | Link |
| ------- | --------- | ------- | ------------|
| fwupd | 1.8.1 | 2018-09-20 | https://fwupd.org/lvfs/devices/com.dell.uefi1610b70e.firmware |
| Dell | 1.10.0 | 2019-08-30 | https://www.dell.com/support/home/uk/en/ukbsdt1/drivers/driversdetails?driverid=116py&oscode=wt64a&productcode=inspiron-15-7567-laptop |

If you look at older versions on the website, fwupd also never received the 1.9.0 BIOS released in May 2019

**Comment by superm1** [comment]
1.10.0 is there now

**Comment by pshem** [comment]
Thank you!
