### ISSUE TITLE
Missing Firmware - Dell Precision 3530 - Please add BIOS 1.5.1

### ISSUE THREAD

**Issue by kgkilc** [fwupd/missing-firmware-dell#7]
For missing firmware please provide the following items:

* Link to firmware update at OEM website
https://downloads.dell.com/FOLDER05351264M/1/Latitude_5X91_Precision_3530_1.5.1.exe
https://downloads.dell.com/FOLDER05377119M/1/Latitude_5X91_Precision_3530_1.5.1.txt

* Firmware release date (if available on OEM website)
Version 1.5.1 - 21 Dec 2018

* Link to the device page on LVFS.
I think it is this page: https://fwupd.org/lvfs/device/479d7d09-78d8-4fb2-af14-ca6ecc80692d

Note: fixes this issue 
- Fixed the issue where the system does not resume from sleep after you undock it from either a Dell WD15 or Dell TB16 docking station with USB power share enabled.

**Comment by superm1** [comment]
1.10.1 is there now, so closing this.
